In [1]:
import os
import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np
import os
import numpy as np
!pip install pycocotools

In [18]:
from pycocotools import mask as cocoMask
def my_dataset_function():
    path = "/Users/mbronars/Documents/sohn/cellSegmentation/detectron2/rawImages/jpg/"
    temp = os.listdir("../pngMasks")
    annotations = []
    for f in temp:
        if ".png" != f[-4:]:
            continue
        #print(f)
        dic = {"file_name":path + f}
        dic["height"] = 308
        dic["width"] = 308
        img = cv.imread("../pngMasks/" + f)
        img = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
        print(img.shape)
        print(img)
        dic["annotations"] = []
        for c in range(1, 256):
            anndic = {}
            anndic["category_id"] = 1
            #anndic["bbox_mode"] = detectron2.structures.BoxMode.XYXY_ABS
            
            a = np.where(img != 0)
            bbox = np.min(a[0]), np.max(a[0]), np.min(a[1]), np.max(a[1])

            #anndic[""]
            mask = (img == [c])
            if mask.any():
                print("pixels of color: " + str(c))
                mask = mask.astype(np.uint8)
                ann = cocoMask.encode(np.asarray(mask, order="F"))
                dic["annotations"].append(anndic)
                a = np.where(mask != 0)
                bbox = np.min(a[0]), np.max(a[0]), np.min(a[1]), np.max(a[1])
                anndic["bbox"] = bbox
        annotations.append(dic)
    return annotations

In [19]:
def my_dataset_tester():
    path = "../imageMasks/"
    temp = os.listdir("../imageMasks")
    files = []
    for f in temp:
        files.append(path+f)
    #print(files)
    return files

In [20]:
files = my_dataset_function()
print(files)

(308, 308)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
pixels of color: 255
(308, 308)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
pixels of color: 235
pixels of color: 255
(308, 308)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
pixels of color: 195
pixels of color: 215
pixels of color: 235
pixels of color: 255
(308, 308)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
pixels of color: 255
(308, 308)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
pixels of color: 235
pixels of color: 255
(308, 308)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
pixe

(308, 308)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
pixels of color: 215
pixels of color: 235
pixels of color: 255
(308, 308)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
pixels of color: 235
pixels of color: 255
(308, 308)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
pixels of color: 235
pixels of color: 255
(308, 308)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
pixels of color: 235
pixels of color: 255
(308, 308)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
pixels of color: 215
pixels of color: 235
pixels of color: 255
(308, 308)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 

In [37]:
import detectron2
from detectron2.data.datasets import register_coco_instances
register_coco_instances("my_dataset_train", files, "json_annotation_train.json", "path/to/image/dir")
#register_coco_instances("my_dataset_val", {}, "json_annotation_val.json", "path/to/image/dir")


ModuleNotFoundError: No module named 'detectron2'

In [ ]:
def my_dataset_function_json: